# Generated by Django 4.0.4 on 2022-04-24 15:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Modificação')),
                ('caminho_arquivo', models.FileField(upload_to=core.models.caminho_upload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holerite',
            fields=[
                ('filepdf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.filepdf')),
                ('mes', models.CharField(choices=[('Jan', 'Janeiro'), ('Fev', 'Feveiro'), ('Mar', 'Março'), ('Abr', 'Abril'), ('Mai', 'Maio'), ('Jun', 'Junho'), ('Jul', 'Julho'), ('Ago', 'Agosto'), ('Set', 'Setembro'), ('Out', 'Outubro'), ('Nov', 'Novembro'), ('Dez', 'Dezembro')], default='Jan', max_length=4)),
                ('ano', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.filepdf',),
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('filepdf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.filepdf')),
                ('mes', models.CharField(choices=[('Jan', 'Janeiro'), ('Fev', 'Feveiro'), ('Mar', 'Março'), ('Abr', 'Abril'), ('Mai', 'Maio'), ('Jun', 'Junho'), ('Jul', 'Julho'), ('Ago', 'Agosto'), ('Set', 'Setembro'), ('Out', 'Outubro'), ('Nov', 'Novembro'), ('Dez', 'Dezembro')], default='Jan', max_length=4)),
                ('ano', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.filepdf',),
        ),
        migrations.CreateModel(
            name='F0001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Modificação')),
                ('modalidade', models.CharField(choices=[('HOL', 'Holerite'), ('PONT', 'Ponto')], default='HOL', max_length=4)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('caminho_arquivo', models.FileField(upload_to=core.models.caminho_upload)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
