# Generated by Django 4.0.4 on 2022-05-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_f0012_f0011_f0010_f0009_f0008_f0007_f0006_f0005_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f0001',
            name='caminho_arquivo',
        ),
    ]
