# Generated by Django 4.0 on 2022-05-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_f0001_caminho_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f0002',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0003',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0004',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0005',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0006',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0007',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0008',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0009',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0010',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0011',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='f0012',
            name='nome',
        ),
        migrations.DeleteModel(
            name='F0001',
        ),
        migrations.DeleteModel(
            name='F0002',
        ),
        migrations.DeleteModel(
            name='F0003',
        ),
        migrations.DeleteModel(
            name='F0004',
        ),
        migrations.DeleteModel(
            name='F0005',
        ),
        migrations.DeleteModel(
            name='F0006',
        ),
        migrations.DeleteModel(
            name='F0007',
        ),
        migrations.DeleteModel(
            name='F0008',
        ),
        migrations.DeleteModel(
            name='F0009',
        ),
        migrations.DeleteModel(
            name='F0010',
        ),
        migrations.DeleteModel(
            name='F0011',
        ),
        migrations.DeleteModel(
            name='F0012',
        ),
    ]
