# Generated by Django 4.0 on 2022-05-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_f0002_nome_remove_f0003_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holerite',
            name='id_user',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='id_user',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
            preserve_default=False,
        ),
    ]
