# Generated by Django 4.0 on 2022-05-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_holerite_id_user_ponto_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.BooleanField(default=True, verbose_name='estado de ativacao'),
        ),
    ]
