# Generated by Django 4.0 on 2022-05-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_funcionario_senha_funcionario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='estado de ativacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='holerite',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionariouser'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionariouser'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
