# Generated by Django 4.0 on 2022-05-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_funcionariouser_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_insercao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_modificacao',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default=str, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
