# Generated by Django 4.0 on 2022-05-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_funcionario_data_insercao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
