# Generated by Django 4.0 on 2022-05-03 01:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
